version: '3.7'

services:
  app:
    image: app_restaurants:v2
    container_name: app_restaurants
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file: .env.development
    ports: 
        - 80:3000
    depends_on:
      - mongodb
      - redis
    restart: always
    networks:
      - ms_nestjs

  microservice-restaurants:
    image: microservice-restaurants:v2
    container_name: smicroservice-restaurants
    build:
      context: ./microservice-restaurants
      dockerfile: Dockerfile
    env_file: .env.development
    depends_on:
      - mongodb
      - redis
    restart: always
    networks:
      - ms_nestjs

  microservice-users:
    image: microservice-users:v2
    container_name: microservice-users
    build:
      context: ./microservice-users
      dockerfile: Dockerfile
    env_file: .env.development
    depends_on:
      - mongodb
      - redis
    restart: always
    networks:
      - ms_nestjs

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
    restart: always
    networks:
      - ms_nestjs

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    expose:
      - 27017
    networks:
      - ms_nestjs

volumes:
  mongodb:

networks:
  ms_nestjs:
